# Generated by Django 4.2.7 on 2024-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
