# Generated by Django 4.2.7 on 2024-10-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_upvoted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvoted_by',
        ),
    ]
